export const PPE_ICON_URLS = {
  'Safety Goggles': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/wear-eye-protection.png',
  'Hearing Protection': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/wear-ear-protection.png',
  'Protective Clothing': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/wear-protective-clothing.png',
  'P3 Masks': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/wear-a-mask.png',
  'Face Shield': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/wear-a-face-shield.png',
  'Respirator Hoods': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/wear-a-safety-harness.png',
  'Connect an earth terminal to the ground': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/connect-an-earth-terminal-to-the-ground.png',
  'Disconnect before carrying out maintenance or repair': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/disconnect-before-carrying-out-maintenance-or-repair.png',
  'Disconnect mains plug from electrical outlet': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/disconnect-mains-plug-from-electrical-outlet.png',
  'Disinfect surface': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/disinfect-surface.png',
  'Disinfect your hands': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/disinfect-your-hands.png',
  'Ensure continuous ventilation': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/ensure-continuous-ventilation.png',
  'Entry only with supervisor outside': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/entry-only-with-supervisor-outside.png',
  'General mandatory action sign': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/general-mandatory-action-sign.png',
  'Install locks and keep locked': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/install-locks-and-keep-locked.png',
  'Install or check guard': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/install-or-check-guard.png',
  'Opaque eye protection must be worn': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/opaque-eye-protection-must-be-worn.png',
  'Place trash in the bin': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/place-trash-in-the-bin.png',
  'Refer to instruction manual': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/refer-to-instruction-manual.png',
  'Secure gas cylinders': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/secure-gas-cylinders.png',
  'Sound your horn': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/sound-your-horn.png',
  'Use barrier cream': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/use-barrier-cream.png',
  'Use breathing equipment': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/use-breathing-equipment.png',
  'Use footbridge': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/use-footbridge.png',
  'Use footwear with antistatic or antispark features': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/use-footwear-with-anti-static-or-anti-spark-features.png',
  'Use gas detector': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/use-gas-detector.png',
  'Use guard to protect from injury from the table saw': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/use-guard-to-protect-from-injury-from-the-table-saw.png',
  'Use handrail': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/use-handrail.png',
  'Use protective apron': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/use-protective-apron.png',
  'Use this walkway': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/use-this-walkway.png',
  'Ventilate before and during entering': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/ventilate-before-and-during-entering.png',
  'Wash your hands': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/wash-your-hands.png',
  'Wear a safety harness': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/wear-a-safety-harness.png',
  'Wear a welding mask': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/wear-a-welding-mask.png',
  'Wear safety belts': 'https://xrjwzlwtublkapjzbljg.supabase.co/storage/v1/object/public/ppe-icons/wear-safety-belts.png'
} as const;