import {
  Anvil,
  Axe,
  Bell,
  Bolt,
  BookUser,
  BrickWall,
  Brush,
  Cable,
  Camera,
  Cctv,
  ChartColumnBig,
  CircleCheckBig,
  CircleParking,
  CirclePoundSterling,
  CirclePower,
  Clipboard,
  ClipboardCheck,
  Cuboid,
  Drill,
  File,
  FileCheck,
  FileText,
  FireExtinguisher,
  Gavel,
  Hammer,
  HardHat,
  House,
  HousePlug,
  Image,
  Info,
  LandPlot,
  Map,
  MapPin,
  Maximize2,
  Megaphone,
  Milestone,
  Move3d,
  PaintBucket,
  PaintRoller,
  Paintbrush,
  Paperclip,
  Pen,
  Pencil,
  PencilRuler,
  Phone,
  Pickaxe,
  Pin,
  Plus,
  Power,
  Radius,
  ReceiptPoundSterling,
  Route,
  Ruler,
  Send,
  ShieldAlert,
  Shovel,
  Sprout,
  SquareMinus,
  SquarePen,
  SquarePlus,
  Stamp,
  TestTube,
  TestTubeDiagonal,
  TreeDeciduous,
  TreePine,
  Trees,
  Wifi,
  Wrench,
  Zap
} from 'lucide-react';
import { IconData } from '../types';

// Available icons for categories - sorted alphabetically
export const CATEGORY_ICONS: IconData[] = [
  { name: 'Anvil', icon: Anvil },
  { name: 'Axe', icon: Axe },
  { name: 'Bell', icon: Bell },
  { name: 'Bolt', icon: Bolt },
  { name: 'BookUser', icon: BookUser },
  { name: 'BrickWall', icon: BrickWall },
  { name: 'Brush', icon: Brush },
  { name: 'Cable', icon: Cable },
  { name: 'Camera', icon: Camera },
  { name: 'Cctv', icon: Cctv },
  { name: 'ChartColumnBig', icon: ChartColumnBig },
  { name: 'CircleCheckBig', icon: CircleCheckBig },
  { name: 'CircleParking', icon: CircleParking },
  { name: 'CirclePoundSterling', icon: CirclePoundSterling },
  { name: 'CirclePower', icon: CirclePower },
  { name: 'Clipboard', icon: Clipboard },
  { name: 'ClipboardCheck', icon: ClipboardCheck },
  { name: 'Cuboid', icon: Cuboid },
  { name: 'Drill', icon: Drill },
  { name: 'File', icon: File },
  { name: 'FileCheck', icon: FileCheck },
  { name: 'FileText', icon: FileText },
  { name: 'FireExtinguisher', icon: FireExtinguisher },
  { name: 'Gavel', icon: Gavel },
  { name: 'Hammer', icon: Hammer },
  { name: 'HardHat', icon: HardHat },
  { name: 'House', icon: House },
  { name: 'HousePlug', icon: HousePlug },
  { name: 'Image', icon: Image },
  { name: 'Info', icon: Info },
  { name: 'LandPlot', icon: LandPlot },
  { name: 'Map', icon: Map },
  { name: 'MapPin', icon: MapPin },
  { name: 'Maximize2', icon: Maximize2 },
  { name: 'Megaphone', icon: Megaphone },
  { name: 'Milestone', icon: Milestone },
  { name: 'Move3d', icon: Move3d },
  { name: 'PaintBucket', icon: PaintBucket },
  { name: 'PaintRoller', icon: PaintRoller },
  { name: 'Paintbrush', icon: Paintbrush },
  { name: 'Paperclip', icon: Paperclip },
  { name: 'Pen', icon: Pen },
  { name: 'Pencil', icon: Pencil },
  { name: 'PencilRuler', icon: PencilRuler },
  { name: 'Phone', icon: Phone },
  { name: 'Pickaxe', icon: Pickaxe },
  { name: 'Pin', icon: Pin },
  { name: 'Plus', icon: Plus },
  { name: 'Power', icon: Power },
  { name: 'Radius', icon: Radius },
  { name: 'ReceiptPoundSterling', icon: ReceiptPoundSterling },
  { name: 'Route', icon: Route },
  { name: 'Ruler', icon: Ruler },
  { name: 'Send', icon: Send },
  { name: 'ShieldAlert', icon: ShieldAlert },
  { name: 'Shovel', icon: Shovel },
  { name: 'Sprout', icon: Sprout },
  { name: 'SquareMinus', icon: SquareMinus },
  { name: 'SquarePen', icon: SquarePen },
  { name: 'SquarePlus', icon: SquarePlus },
  { name: 'Stamp', icon: Stamp },
  { name: 'TestTube', icon: TestTube },
  { name: 'TestTubeDiagonal', icon: TestTubeDiagonal },
  { name: 'TreeDeciduous', icon: TreeDeciduous },
  { name: 'TreePine', icon: TreePine },
  { name: 'Trees', icon: Trees },
  { name: 'Wifi', icon: Wifi },
  { name: 'Wrench', icon: Wrench },
  { name: 'Zap', icon: Zap }
];
