export const UK_COUNTIES = [
  'Aberdeen',
  'Aberdeenshire',
  'Anglesey',
  'Angus',
  'Argyll and Bute',
  'Armagh',
  'Bath and North East Somerset',
  'Bedfordshire',
  'Belfast',
  'Berkshire',
  'Birmingham',
  'Blaenau Gwent',
  'Bradford',
  'Bridgend',
  'Brighton and Hove',
  'Bristol',
  'Buckinghamshire',
  'Canterbury',
  'Carlisle',
  'Caerphilly',
  'Cambridgeshire',
  'Cardiff',
  'Carmarthenshire',
  'Ceredigion',
  'Chelmsford',
  'Cheshire',
  'Chester',
  'Chichester',
  'Clackmannanshire',
  'Conwy',
  'Cornwall',
  'Coventry',
  'Cumbria',
  'Denbighshire',
  'Derbyshire',
  'Devon',
  'Dorset',
  'Dumfries and Galloway',
  'Dundee',
  'Durham',
  'East Ayrshire',
  'East Dunbartonshire',
  'East Lothian',
  'East Renfrewshire',
  'East Riding of Yorkshire',
  'East Sussex',
  'Edinburgh',
  'Essex',
  'Exeter',
  'Falkirk',
  'Fife',
  'Flintshire',
  'Glasgow',
  'Gloucestershire',
  'Greater London',
  'Greater Manchester',
  'Gwynedd',
  'Hampshire',
  'Herefordshire',
  'Hertfordshire',
  'Highlands',
  'Inverclyde',
  'Isle of Wight',
  'Kent',
  'Lancashire',
  'Leicestershire',
  'Lincolnshire',
  'Liverpool',
  'Londonderry',
  'Merseyside',
  'Merthyr Tydfil',
  'Midlothian',
  'Monmouthshire',
  'Moray',
  'Neath Port Talbot',
  'Newcastle upon Tyne',
  'Newport',
  'Newry',
  'Norfolk',
  'North Ayrshire',
  'North Lanarkshire',
  'North Yorkshire',
  'Northamptonshire',
  'Northumberland',
  'Nottinghamshire',
  'Orkney Islands',
  'Oxfordshire',
  'Pembrokeshire',
  'Perth and Kinross',
  'Powys',
  'Renfrewshire',
  'Rhondda Cynon Taff',
  'Rutland',
  'Salford',
  'Scottish Borders',
  'Shetland Islands',
  'Shropshire',
  'Somerset',
  'South Ayrshire',
  'South Lanarkshire',
  'South Yorkshire',
  'Staffordshire',
  'Stirling',
  'Sunderland',
  'Suffolk',
  'Surrey',
  'Swansea',
  'Torfaen',
  'Tyne and Wear',
  'Vale of Glamorgan',
  'Warwickshire',
  'West Dunbartonshire',
  'West Lothian',
  'West Midlands',
  'West Sussex',
  'West Yorkshire',
  'Western Isles',
  'Wiltshire',
  'Worcestershire',
  'Wrexham',
].sort();

export const FORM_STEPS = {
  CONTRACT: 1,
  CUSTOMER: 2,
  PROJECT: 3,
  DESCRIPTION: 4,
  SUBCONTRACTORS: 5,
  FINANCIAL: 6
} as const;

export const STEP_LABELS = [
  'Contract', 
  'Customer', 
  'Project', 
  'Description', 
  'Subcontractors', 
  'Financial'
];

export const TOTAL_STEPS = 6;

export const DEFAULT_BUILDER_RESPONSIBILITIES = `• Foundation and groundwork design / calculations 
• Full design and build package for the project
• Project management of project from start date
• Foundation works 
• Manufactured and installed as per order contract 
• Canopies manufactured and installed as per order contract`;

export const DEFAULT_STATUTORY_INTEREST_RATE = '8% plus the Bank of England base rate for business to business transactions';

export const DEFAULT_COMPANY_SETTINGS = {
  name: 'ON POINT GROUNDWORK',
  logo_url: '',
  address_line1: '',
  town: '',
  county: '',
  post_code: '',
  phone: '',
  email: '',
  public_liability: '5,000,000',
  employers_liability: '10,000,000'
};